### ISSUE TITLE
SyntaxError: invalid syntax, File "extras/pokemontools/gfx.py", line 71

### ISSUE THREAD

**Issue by wiseguy12851** [pret/pokemon-reverse-engineering-tools#106]
Not sure which repo to post this issue in. I'm using pret/pokemontcg but the issue is happening in pret/pokemon-reverse-engineering-tools or extras submodule.

Upon running make I get this error:
```
  File "extras/pokemontools/gfx.py", line 71
    tiles = sorted(enumerate(tiles), key= lambda (i, tile): i % width)
                                                 ^
SyntaxError: invalid syntax
Makefile:20: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1
```

But i see that the current extras is referencing an old version of pokemon-reverse-engineering-tools. Maybe I can update it to the newest version or perhaps the whole project has been abandoned in which case I shouldn't really do much with it.

**Comment by wiseguy12851** [comment]
I updated to latest commit and got this message now

```
Traceback (most recent call last):
  File "extras/pokemontools/gfx.py", line 7, in <module>
    from . import png
SystemError: Parent module '' not loaded, cannot perform relative import
Makefile:20: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1
```

This is a new error and I see its already been documented here so perhaps I'll wait. Good luck.

**Comment by Sanqui** [comment]
Try the old version with Python 2.
